// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bread: typeof import('./src/components/Bread.vue')['default']
    DeleteModal: typeof import('./src/components/modal/DeleteModal.vue')['default']
    EditAddModal: typeof import('./src/components/modal/EditAddModal.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/SidebarNav.vue')['default']
  }
}
